name: Pallid Sturgeon
description: Pallid Sturgeon Issue
title: "-- Please provide brief summary --"
labels: ["Pallid", "Open"]
type: "Bug"
body:
  - type: dropdown
    id: env
    attributes:
      label: Environment
      options:
        - TEST
        - PROD
    validations:
      required: true
    
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: 
        - High
        - Medium
        - Low
    validations:
      required: true
      
  - type: textarea
    id: background
    attributes:
      label: Background Information
      description: "Provide details on what the issue is, how to replicate, page names & URLs, copy/paste or upload any necessary screenshots into the text area."
    validations: 
      required: true

