name: Pallid Sturgeon
description: Please insert an issue regarding Pallid Sturgeon
title: "Pallid: <summary>"
labels: ["Pallid"]
body:
- type: dropdown
  id: env
  attributes:
    label: Environment
    options:
      - TEST
      - PROD

- type: input
  id: url
  attributes: 
    label: URL Information
    description: "Please insert information regarding location of issue"
    placeholder: "i.e. <URL> <this graph>"

- type: textarea
  id: photos
  attributes:
    label: Uploads
    description: "Drag and drop images here."
    placeholder: "Here"
    render: markdown
    
