name: client issue
description: Blah Blah Blah
title: "[PROJECT]: <summary>"
labels: ["test"]
body:
- type: dropdown
  id: client
  attributes:
    label: Client issue?
    options:
      - Test 1
      - Test
      - Test

